### PR TITLE
add(i18n): Japanese translation

### PR DESCRIPTION
**Pull request by SakuraSa233**

### CODE REVIEW

**Comment by tobiichiamane** [comment]
Thanks for your contributions. Some of the strings may be too long to fit in the UI elements, which may cause some funky display problems, but shouldn't be too much of a problem, and this issue also exists in my English translations. 
I may have to redesign part of the UI to resolve the issue. 

Anyway, I'll test the compiled artifact and merge your PR if there is no more problems.

**Comment by tobiichiamane** [comment]
And I've submitted the app to the Store earlier this day, so your contributions will be published to users along with the next update.

**Comment by SakuraSa233** [comment]
<-- Never found it in Microsoft Store and just install it from release.

**Comment by tobiichiamane** [comment]
> <-- Never found it in Microsoft Store and just install it from release.

Store reviewers say that this app contains "sexually explicit contents" and are not allowed in the store. They've taken down several of my update submissions since the first generation of this app, so I made it unavailable in the Store. 
Though, I wrote a detailed email for them earlier this day, illustrating why it is impossible to filter those contents, and indicating that I've already included this issue in the age rating systems, so they agreed to let me update this app with the so called "sexually explicit contents".
Once the submission is passed, I'll make it available and visible again.

**Comment by tobiichiamane** [comment]
hmmmmmm seems like you forgot to include the language resource file in the solution. I'll merge first, and solve the problem myself. 
Thanks for your contributions.

**Comment by tobiichiamane** [comment]
@all-contributors please add @SakuraSa233 for translation

**Pull request merged**
